# -*- coding: utf-8 -*-
"""exercicio_pratico1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_STYTXc4fOCBMPCwzJ-Bg9ijsoBO2NGN

#Calculadora Inteligente
"""

num1 = float(input('Digite o primeiro número: '))

operador = input('Digite o operador (+, -, *, /, %): ')

num2 = float(input('Digite o segundo número: '))

if operador == '+':
  print(num1 + num2)
elif operador == '-':
  print(num1 - num2)
elif operador == '*':
  print(num1 * num2)
elif operador == '/':
  if num2 == 0:
    print('Não é possível dividir por zero')
  else:
    print(num1 / num2)
elif operador == '%':
  print(num1 * num2 / 100)
else:
  print('Operação inválida')